const baseProperties = require('./properties');

module.exports = {
    ...baseProperties,
    language: 'de',
    title: 'Schwellenländeranleihen',
    translation: {
        email_error: 'Ihre Email Adresse ist nicht korrekt',
        code_error:
            'Das Feld ist obligatorisch und sollte aus Zahlen bestehen und genau 9 Stellen enthalten',
        title_error: 'Title Feld ist obligatorisch',
        provide_required: 'Bitte füllen Sie alle Pflichtfelder aus',
        placeholder: 'Code*, Beispiel 457859683',
        residence: 'Land auswählen',
        labels: {
            radio_label: 'Titel',
            first_name: 'Vorname',
            last_name: 'Nachname',
            company: 'Firma',
            street_house: 'Strasse, Hausnummer',
            city: 'Stadt',
            email: 'E-Mail',
            tel: 'Telefon',
            city_2: 'Stadt',
            zip: 'Postleitzahl',
        },
        countries: {
            AF: 'Afghanistan',
            EG: 'Ägypten',
            AX: 'Älandinseln',
            AL: 'Albanien',
            DZ: 'Algerien',
            AS: 'Amerikanisch-Samoa',
            VI: 'Amerikanische Jungferninseln',
            UM: 'Amerikanische Ãœberseeinseln',
            AD: 'Andorra',
            AO: 'Angola',
            AI: 'Anguilla',
            AQ: 'Antarktis',
            AG: 'Antigua und Barbuda',
            GQ: 'Äquatorialguinea',
            AR: 'Argentinien',
            AM: 'Armenien',
            AW: 'Aruba',
            AC: 'Ascension',
            AZ: 'Aserbaidschan',
            ET: 'Äthiopien',
            AU: 'Australien',
            QO: 'Äusseres Ozeanien',
            BS: 'Bahamas',
            BH: 'Bahrain',
            BD: 'Bangladesch',
            BB: 'Barbados',
            BY: 'Belarus',
            BE: 'Belgien',
            BZ: 'Belize',
            BJ: 'Benin',
            BM: 'Bermuda',
            BT: 'Bhutan',
            BO: 'Bolivien',
            BQ: 'Bonaire, Sint Eustatius und Saba',
            BA: 'Bosnien und Herzegowina',
            BW: 'Botsuana',
            BV: 'Bouvetinsel',
            BR: 'Brasilien',
            VG: 'Britische Jungferninseln',
            IO: 'Britisches Territorium im Indischen Ozean',
            BN: 'Brunei Darussalam',
            BG: 'Bulgarien',
            BF: 'Burkina Faso',
            BI: 'Burundi',
            CV: 'Cabo Verde',
            EA: 'Ceuta und Melilla',
            CL: 'Chile',
            CN: 'China',
            CP: 'Clipperton-Insel',
            CK: 'Cookinseln',
            CR: 'Costa Rica',
            CW: 'Curaçao',
            CI: 'Côte d’Ivoire',
            DE: 'Deutschland',
            DG: 'Diego Garcia',
            DM: 'Dominica',
            DO: 'Dominikanische Republik',
            DJ: 'Dschibuti',
            DK: 'Dänemark',
            EC: 'Ecuador',
            SV: 'El Salvador',
            ER: 'Eritrea',
            EE: 'Estland',
            SZ: 'Eswatini',
            EU: 'Europäische Union',
            EZ: 'Eurozone',
            FK: 'Falklandinseln',
            FJ: 'Fidschi',
            FI: 'Finnland',
            FR: 'Frankreich',
            GF: 'Französisch-Guayana',
            PF: 'Französisch-Polynesien',
            TF: 'Französische Süd- und Antarktisgebiete',
            FO: 'Färöer',
            GA: 'Gabun',
            GM: 'Gambia',
            GE: 'Georgien',
            GH: 'Ghana',
            GI: 'Gibraltar',
            GD: 'Grenada',
            GR: 'Griechenland',
            GL: 'Grönland',
            GP: 'Guadeloupe',
            GU: 'Guam',
            GT: 'Guatemala',
            GG: 'Guernsey',
            GN: 'Guinea',
            GW: 'Guinea-Bissau',
            GY: 'Guyana',
            HT: 'Haiti',
            HM: 'Heard und McDonaldinseln',
            HN: 'Honduras',
            IN: 'Indien',
            ID: 'Indonesien',
            IQ: 'Irak',
            IR: 'Iran',
            IE: 'Irland',
            IS: 'Island',
            IM: 'Isle of Man',
            IL: 'Israel',
            IT: 'Italien',
            JM: 'Jamaika',
            JP: 'Japan',
            YE: 'Jemen',
            JE: 'Jersey',
            JO: 'Jordanien',
            KY: 'Kaimaninseln',
            KH: 'Kambodscha',
            CM: 'Kamerun',
            CA: 'Kanada',
            IC: 'Kanarische Inseln',
            KZ: 'Kasachstan',
            QA: 'Katar',
            KE: 'Kenia',
            KG: 'Kirgisistan',
            KI: 'Kiribati',
            CC: 'Kokosinseln',
            CO: 'Kolumbien',
            KM: 'Komoren',
            CG: 'Kongo-Brazzaville',
            CD: 'Kongo-Kinshasa',
            XK: 'Kosovo',
            HR: 'Kroatien',
            CU: 'Kuba',
            KW: 'Kuwait',
            LA: 'Laos',
            LS: 'Lesotho',
            LV: 'Lettland',
            LB: 'Libanon',
            LR: 'Liberia',
            LY: 'Libyen',
            LI: 'Liechtenstein',
            LT: 'Litauen',
            LU: 'Luxemburg',
            MG: 'Madagaskar',
            MW: 'Malawi',
            MY: 'Malaysia',
            MV: 'Malediven',
            ML: 'Mali',
            MT: 'Malta',
            MA: 'Marokko',
            MH: 'Marshallinseln',
            MQ: 'Martinique',
            MR: 'Mauretanien',
            MU: 'Mauritius',
            YT: 'Mayotte',
            MX: 'Mexiko',
            FM: 'Mikronesien',
            MC: 'Monaco',
            MN: 'Mongolei',
            ME: 'Montenegro',
            MS: 'Montserrat',
            MZ: 'Mosambik',
            MM: 'Myanmar',
            NA: 'Namibia',
            NR: 'Nauru',
            NP: 'Nepal',
            NC: 'Neukaledonien',
            NZ: 'Neuseeland',
            NI: 'Nicaragua',
            NL: 'Niederlande',
            NE: 'Niger',
            NG: 'Nigeria',
            NU: 'Niue',
            KP: 'Nordkorea',
            MK: 'Nordmazedonien',
            NF: 'Norfolkinsel',
            NO: 'Norwegen',
            MP: 'Nördliche Marianen',
            OM: 'Oman',
            AT: 'Österreich',
            PK: 'Pakistan',
            PW: 'Palau',
            PS: 'Palästinensische Autonomiegebiete',
            PA: 'Panama',
            PG: 'Papua-Neuguinea',
            PY: 'Paraguay',
            PE: 'Peru',
            PH: 'Philippinen',
            PN: 'Pitcairninseln',
            PL: 'Polen',
            PT: 'Portugal',
            XA: 'Pseudo-Akzente',
            XB: 'Pseudo-Bidi',
            PR: 'Puerto Rico',
            MD: 'Republik Moldau',
            RW: 'Ruanda',
            RO: 'Rumänien',
            RU: 'Russland',
            RE: 'Réunion',
            SB: 'Salomonen',
            ZM: 'Sambia',
            WS: 'Samoa',
            SM: 'San Marino',
            SA: 'Saudi-Arabien',
            SE: 'Schweden',
            CH: 'Schweiz',
            SN: 'Senegal',
            RS: 'Serbien',
            SC: 'Seychellen',
            SL: 'Sierra Leone',
            ZW: 'Simbabwe',
            SG: 'Singapur',
            SX: 'Sint Maarten',
            SK: 'Slowakei',
            SI: 'Slowenien',
            SO: 'Somalia',
            HK: 'Sonderverwaltungsregion Hongkong',
            MO: 'Sonderverwaltungsregion Macau',
            ES: 'Spanien',
            SJ: 'Spitzbergen und Jan Mayen',
            LK: 'Sri Lanka',
            BL: 'St. Barthélemy',
            SD: 'Sudan',
            SR: 'Suriname',
            SY: 'Syrien',
            ST: 'São Tomé und Príncipe',
            ZA: 'Südafrika',
            GS: 'Südgeorgien und die Südlichen Sandwichinseln',
            KR: 'Südkorea',
            SS: 'Südsudan',
            TJ: 'Tadschikistan',
            TW: 'Taiwan',
            TZ: 'Tansania',
            TH: 'Thailand',
            TL: 'Timor-Leste',
            TG: 'Togo',
            TK: 'Tokelau',
            TO: 'Tonga',
            TT: 'Trinidad und Tobago',
            TA: 'Tristan da Cunha',
            TD: 'Tschad',
            CZ: 'Tschechien',
            TN: 'Tunesien',
            TM: 'Turkmenistan',
            TC: 'Turks- und Caicosinseln',
            TV: 'Tuvalu',
            TR: 'Türkei',
            UG: 'Uganda',
            UA: 'Ukraine',
            HU: 'Ungarn',
            UY: 'Uruguay',
            UZ: 'Usbekistan',
            VU: 'Vanuatu',
            VA: 'Vatikanstadt',
            VE: 'Venezuela',
            AE: 'Vereinigte Arabische Emirate',
            US: 'Vereinigte Staaten',
            GB: 'Vereinigtes Königreich',
            VN: 'Vietnam',
            WF: 'Wallis und Futuna',
            CX: 'Weihnachtsinsel',
            EH: 'Westsahara',
            CF: 'Zentralafrikanische Republik',
            CY: 'Zypern',
        },
        dropdown: {
            Austria: 'Austria',
            Dubai: 'Dubai',
            Guernsey: 'Guernsey',
            Hong_Kong: 'Hong Kong',
            India: 'India',
            Ireland: 'Ireland',
            Israel: 'Israel',
            Luxembourg: 'Luxembourg',
            Monaco: 'Monaco',
            Singapore: 'Singapore',
            South_Africa: 'South Africa',
            Spain: 'Spain',
            Switzerland: 'Switzerland',
            United_Arab_Emirates: 'United Arab Emirates',
            United_Kingdom: 'United Kingdom',
            Uruguay: 'Uruguay',
        },
    },
};
